# Generated by Django 2.2 on 2021-10-25 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20211025_1326'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.IntegerField()),
                ('quan', models.IntegerField()),
                ('prodt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.products')),
            ],
        ),
    ]
