# Generated by Django 2.2 on 2021-10-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='cart_id',
            new_name='c_id',
        ),
    ]
