# Generated by Django 2.2 on 2021-10-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20211027_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='c_id',
            new_name='cart_id',
        ),
    ]
