# Generated by Django 2.2 on 2021-11-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20211028_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='c_id',
            new_name='cart_id',
        ),
    ]
